version: "3.9"

volumes:
  repository:


services:
  bot:
    build:
      context: .
      dockerfile: bot.Dockerfile
    environment:
      - TG_TOKEN=${TG_TOKEN}
      - TG_CHAT_ID=${TG_CHAT_ID}
    command: ["python", "scheduler.py"]
    volumes:
      - repository:/home/git/flats-searcher/src/data
